# Generated by Django 5.2.7 on 2025-11-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipZi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescurtare', models.CharField(max_length=10)),
                ('tip_zi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('functie', models.CharField(max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('adresa', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('locatie', models.TextField(blank=True, null=True)),
                ('ora_incepere', models.TimeField()),
                ('ora_sfarsit', models.TimeField()),
                ('ora_pauza', models.IntegerField(help_text='Durata pauzei în minute')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angajati', to='Time_Tracker_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Pontaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luna', models.CharField(max_length=20)),
                ('an', models.DateField()),
                ('ora_start', models.TimeField()),
                ('ora_sfarsit', models.TimeField()),
                ('pauza_masa', models.IntegerField(help_text='Durata pauzei în minute')),
                ('data', models.DateField()),
                ('ore_lucrate', models.IntegerField()),
                ('ore_lucru_suplimentare', models.IntegerField()),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontaje', to='Time_Tracker_app.angajat')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontaje', to='Time_Tracker_app.tipzi')),
            ],
        ),
    ]
