# Generated by Django 5.2.7 on 2026-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10),
        ),
    ]
