# Generated by Django 5.2.7 on 2026-03-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0002_alter_angajat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='status',
            field=models.CharField(choices=[('activ', 'Activ'), ('inactiv', 'Inactiv'), ('suspendat', 'Suspendat')], default='activ', max_length=10),
        ),
        migrations.CreateModel(
            name='Amprenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.PositiveIntegerField(unique=True)),
                ('activ', models.BooleanField(default=True)),
                ('angajat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Time_Tracker_app.angajat')),
            ],
        ),
    ]
