# Generated by Django 5.2.7 on 2026-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0003_alter_angajat_status_amprenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontaj',
            name='ore_lucrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='ore_lucru_suplimentare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
