# Generated by Django 5.2.7 on 2026-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0004_alter_pontaj_ore_lucrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontaj',
            name='ore_lucrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='ore_lucru_suplimentare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
