# Generated by Django 5.2.7 on 2026-03-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0005_alter_pontaj_ore_lucrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerereAmprenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mesaj', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri_amprenta', to='Time_Tracker_app.angajat')),
            ],
        ),
    ]
