# Generated by Django 5.2.7 on 2026-03-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0006_cerereamprenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontaj',
            name='ore_lucrate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='ore_lucru_suplimentare',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
