# Generated by Django 5.2.7 on 2026-04-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0008_cererestergereamprenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concediu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('durata', models.IntegerField(help_text='Durata concediului în zile')),
                ('an_concediu', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documente_concedii/')),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedii', to='Time_Tracker_app.angajat')),
                ('tip_concediu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedii', to='Time_Tracker_app.tipzi')),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
