# Generated by Django 5.2.7 on 2026-04-06 18:36

import Time_Tracker_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0009_concediu_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcediuAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Time_Tracker_app.models.saving_concediu_attachments)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='concediu',
            name='document',
        ),
        migrations.AddField(
            model_name='concediu',
            name='attach',
            field=models.ManyToManyField(blank=True, to='Time_Tracker_app.concediuattach'),
        ),
    ]
