# Generated by Django 5.2.7 on 2026-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0010_concediuattach_remove_concediu_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontaj',
            name='ora_sfarsit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='ora_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
