# Generated by Django 5.2.7 on 2026-04-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0011_alter_pontaj_ora_sfarsit_alter_pontaj_ora_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontaj',
            name='concediu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontaje_generate', to='Time_Tracker_app.concediu'),
        ),
    ]
