# Generated by Django 5.2.7 on 2026-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0012_pontaj_concediu'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pontaj',
            constraint=models.UniqueConstraint(fields=('angajat', 'data'), name='unique_pontaj_per_angajat_pe_zi'),
        ),
    ]
