# Generated by Django 5.2.7 on 2026-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0013_pontaj_unique_pontaj_per_angajat_pe_zi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipzi',
            name='este_concediu',
            field=models.BooleanField(default=False),
        ),
    ]
