# Generated by Django 5.2.7 on 2026-04-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0014_tipzi_este_concediu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concediu',
            name='attach',
        ),
    ]
