# Generated by Django 5.2.7 on 2026-04-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0015_remove_concediu_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='concediuattach',
            name='concediu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach', to='Time_Tracker_app.concediu'),
        ),
    ]
