# Generated by Django 5.2.7 on 2026-06-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Tracker_app', '0016_concediuattach_concediu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concediu',
            name='tip_concediu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concedii', to='Time_Tracker_app.tipzi'),
        ),
        migrations.AlterField(
            model_name='pontaj',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pontaje', to='Time_Tracker_app.tipzi'),
        ),
    ]
